[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lofar_facet_selfcal"
version = "11.3.0"
description = "LOFAR facet selfcal"

[project.scripts]
h5_merger = "h5_helpers.h5_merger:main"
facetselfcal = "install.wrapper:main"

[tool.setuptools]
packages = ["h5_helpers", "install"]
